### ISSUE TITLE
PDDL Output

### ISSUE THREAD

**Issue by mikand** [aiplan4eu/upf#13]
### User Story
As a **planning expert/enthusiast** I want to be able to emit a PDDL representation of a planning problem modeled in the `upf` library to interoperate with an external planner manually.

For example, I want to dump a planning model that is generated from a TSB to include it in a planning competition or to experiment with an off-the-shelf planner that is not interfaced with the UPF

### Acceptance Criteria

- [ ] The generated PDDL is acceptable by major planners in the category (for now, numeric and classical planners)
- [ ] If needed, options are provided to enable/disable specific dialects
- [ ] The PDDL can be saved to an actual file, showed on the screen or in file-like object for code-level reuse / network transmission

### Additional Material

- https://github.com/remykarem/py2pddl
- http://users.cecs.anu.edu.au/~patrik/pddlman/writing.html
- https://planning.wiki/ref/pddl
- http://editor.planning.domains/

An interface like 
```python
from upf.io import PDDLPrinter
printer = PDDLPrinter(problem) 
printer.write_domain("domain.pddl")
printer.write_problem("instance.pddl")
``` 
could be suitable.

### Attention Points

- Using a template library like [Jinja](https://jinja.palletsprojects.com/en/3.0.x/) could be a good idea
- Avoid writing a "valley of prints"
- Avoid excessive string concatenation (i.e., `a + " - " + b`)

**Comment by haz** [comment]
Again, `tarski` to the rescue ;)
- https://tarski.readthedocs.io/en/latest/notebooks/defining-your-first-planning-problem.html
- http://mulab.ai/tarski/io/fstrips.html#tarski.io.fstrips.FstripsWriter.write

We have some decent experience in building domains/problems dynamically, and then writing out to PDDL.
