### ISSUE TITLE
Closed World Assumption

### ISSUE THREAD

**Issue by hstairs** [aiplan4eu/upf#17]
As a PDDL user, I would find it nice to have a way to express the initial state in CWA through UPF. Maybe we could make it optional, but, at least for propositional variables, this should be quite straightforward, and very handy especially for problems with a large number of objects. For instance, when there is the need to model when two positions are (not) connected.

**Comment by mikand** [comment]
I think that something like:
```python
Location = UserType('Location')

# Without the `default_initial_value=False` we would have to initialize all the N robot_ats in the initial state
robot_at = upf.Fluent('robot_at', BoolType(), [Location], default_initial_value=False) 

# Without the `default_initial_value=-1` we would have to initialize all the N*N distances in the initial state
distance = upf.Fluent('robot_at', RealType(), [Location, Location], default_initial_value=-1) 

move = upf.Action('move', l_from=Location, l_to=Location)
l_from = move.parameter('l_from')
l_to = move.parameter('l_to')
move.add_precondition(Not(Equals(l_from, l_to)))
move.add_precondition(GE(distance(l_from, l_to), 0))
move.add_precondition(robot_at(l_from))
move.add_precondition(Not(robot_at(l_to)))
move.add_effect(robot_at(l_from), False)
move.add_effect(robot_at(l_to), True)

N = 10
locations = [upf.Object(f'l{i}', Location) for i in range(N)] # create objects l0...lN-1
problem = upf.Problem('robot')
problem.add_fluent(robot_at)
problem.add_action(move)
problem.add_objects(locations)
problem.set_initial_value(robot_at(l1), True)
for i in range(N-1):
    problem.set_initial_value(distance(locations[i], locations[i+1]), 10)
problem.add_goal(robot_at(l9))
```

@hstairs Do you think this is acceptable?
@alvalentini Implementation ideas?

**Comment by mikand** [comment]
In a second thought, we could maybe put the `default_initial_value=X` in the `problem.add_fluent()` method. This could be easier to implement and also more flexible...
```python
Location = UserType('Location')
robot_at = upf.Fluent('robot_at', BoolType(), [Location]) 
distance = upf.Fluent('robot_at', RealType(), [Location, Location]) 

move = upf.Action('move', l_from=Location, l_to=Location)
l_from = move.parameter('l_from')
l_to = move.parameter('l_to')
move.add_precondition(Not(Equals(l_from, l_to)))
move.add_precondition(GE(distance(l_from, l_to), 0))
move.add_precondition(robot_at(l_from))
move.add_precondition(Not(robot_at(l_to)))
move.add_effect(robot_at(l_from), False)
move.add_effect(robot_at(l_to), True)

N = 10
locations = [upf.Object(f'l{i}', Location) for i in range(N)] # create objects l0...lN-1
problem = upf.Problem('robot')
problem.add_fluent(robot_at, default_initial_value=False)
problem.add_fluent(distance, default_initial_value=-1)
problem.add_action(move)
problem.add_objects(locations)
problem.set_initial_value(robot_at(l1), True)
for i in range(N-1):
    problem.set_initial_value(distance(locations[i], locations[i+1]), 10)
problem.add_goal(robot_at(l9))
```

**Comment by alvalentini** [comment]
I like the second proposal.
We can store the default values in a dedicated map inside the Problem class.

**Comment by hstairs** [comment]
I like the second better because that way the default value is problem specific and not universal. I can use the same fluent for different problems and have different default values. Yet, if that remains the same, I need to specify that default behavior every time. Do you guys think it can be a good idea to have both things with different scopes, i.e. universal vs problem specific default values?

**Comment by mikand** [comment]
@hstairs What about having adding to the second proposal a "default for defaults" in the `Problem` object?

something like:
```python
...
problem = upf.Problem('robot', initial_defaults={BoolType(): False, RealType():-1, IntType():None})
```
that (unless specified otherwise in the `add_fluent` or by `set_initial_value`) sets all predicates to false and all rational fluents to  -1 and instead requires explicit initialization for integers?

**Note**: `initial_default_value={BoolType(): False, RealType():Undefined, Inttype(): Undefied}` should coincide with the PDDL behavior (except that for now we do not support the `Undefined`)

**Comment by hstairs** [comment]
I like the default for defaults! But yet this is something that can be made universal, too. No? Maybe we can think of this feature in the future if it is really necessary. Just to be clear, my use case is when one has several problem instances but always the same domain/universe, and all problems adopt the same default values.

**Comment by mikand** [comment]
I thought a bit about this. If we go for the "default of defaults" it should be easy to have a family of problems.
Either we do:
```python
mydefaults = {BoolType(): False, RealType():-1, IntType():None}
problem1 = upf.Problem('robot1', initial_defaults=mydefaults)
problem2 = upf.Problem('robot2', initial_defaults=mydefaults)
```
or we can even use inheritance:
```python
class MyProblemKind(upf.Problem):
    def __init__(self, *args, **kwargs):
        assert 'initial_defaults' not in kwargs
        upf.Problem.__init__(self, *args, initial_defaults={BoolType(): False, RealType():-1, IntType():None}, **kwargs) 
        # Or we can have a mechanism to force these defaults (e.g. with a setter) after the initialization of self

problem1 = MyProblemKind('robot1')
problem2 = MyProblemKind('robot2')
```

@hstairs What do you think?

**Comment by hstairs** [comment]
Yes I think that will do. Thanks!
